name: daily-task


on:
  
  workflow_dispatch: # 手动触发
  schedule: # 计划任务触发
    - cron: '0 16 * * *' 
    # cron表达式，时区是UTC时间，比我们早8小时，如上所表示的是每天0点0分（24点整）
    # 建议每个人通过设置 GitHub Environments 的方式来设定为自己的目标运行时间（详细设置方法见文档说明）
    

jobs:
  run-bilibili-tool:

    runs-on: ubuntu-latest

    environment: Production

    steps:

    # 输出IP
    - name: IP
      run: sudo curl ifconfig.me

    # 设置服务器时区为东八区 
    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    # 检出
    - name: Checkout
      uses: actions/checkout@v2
      
    # .Net 环境
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    # 发布
    - name: Publish
      run: |
        cd ./src/Ray.BiliBiliTool.Console
        dotnet publish --configuration Release --self-contained false --output ./bin/Publish/net5-dependent
       
    # 运行
    - name: Run APP
      env:
        ASPNETCORE_ENVIRONMENT: ${{secrets.ENV}} # 运行环境
      run: |
        cd ./src/Ray.AutoTask/bin/Publish/net5-dependent
        dotnet Ray.AutoTask.dll -closeConsoleWhenEnd=1
